"""add_analysis_jobs_table

Revision ID: 21bdae5b1254
Revises: 60866041d61d
Create Date: 2026-04-07 20:31:06.004198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bdae5b1254'
down_revision: Union[str, Sequence[str], None] = '60866041d61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('player_color', sa.String(length=1), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
