"""initial_schema

Revision ID: 60866041d61d
Revises: 
Create Date: 2026-04-04 16:20:01.434010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60866041d61d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pgn_raw', sa.Text(), nullable=False),
    sa.Column('white', sa.String(length=100), nullable=True),
    sa.Column('black', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('opening', sa.String(length=200), nullable=True),
    sa.Column('date_played', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_name')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('game_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('player_color', sa.String(length=1), nullable=False),
    sa.Column('acpl', sa.Float(), nullable=True),
    sa.Column('acpl_opening', sa.Float(), nullable=True),
    sa.Column('acpl_middlegame', sa.Float(), nullable=True),
    sa.Column('acpl_endgame', sa.Float(), nullable=True),
    sa.Column('blunders', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('inaccuracies', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('uci', sa.String(length=10), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('fen_after', sa.Text(), nullable=True),
    sa.Column('eval_cp', sa.Integer(), nullable=True),
    sa.Column('best_move', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('analyses')
    op.drop_table('player_profiles')
    op.drop_table('games')
    # ### end Alembic commands ###
